name: neom_image_editor
description: Image Editor for Open Neom.
version: 1.1.2
homepage: https://github.com/Open-Neom/neom_image_editor
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Open-Neom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Open-Neom/neom_commons.git

  image_cropper: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
